<font color="blue" size=5><b>Numpy-2</b></font>

In [1]:
import numpy as np

In [3]:
a = np.random.randint(1,50,(3,4))
a

array([[14,  7, 47,  6],
       [23, 24, 26, 15],
       [31,  6, 29,  2]])

<font color="red" size=3><b>Flatten array</b></font>

In [4]:
a.flatten()

array([14,  7, 47,  6, 23, 24, 26, 15, 31,  6, 29,  2])

In [5]:
a.reshape(-1)

array([14,  7, 47,  6, 23, 24, 26, 15, 31,  6, 29,  2])

<font color="red" size=3><b>Expands dimension</b></font>

In [9]:
a1 = np.expand_dims(a, axis=0) # adds one dimension to existing dimention
print(a1.ndim)

3


In [10]:
a2 = np.expand_dims(a,axis=1)
print(a2.ndim)

3


<font color="red" size=3><b>Reduces dimension</b></font>

In [13]:
a3 = np.squeeze(a1)
print(a3.ndim)

2


<font color="red" size=3><b>Repeats element</b></font>

In [14]:
b = np.array([1,2,3,4])
np.repeat(b,3) # repeats each element n times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

<font color="red" size=3><b>Rolls elements of array</b></font>

In [16]:
np.roll(b, 2) # similar to shift operator

array([3, 4, 1, 2])

<font color="red" size=3><b>Converts elements of array to diagonal matrix</b></font>

In [17]:
np.diag(b)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

<font color="red" size=3><b>Binary operations</b></font>

In [18]:
arr1 = np.random.randint(1,10,(3,4))
arr1

array([[2, 4, 1, 1],
       [4, 6, 4, 5],
       [7, 9, 6, 1]])

In [19]:
arr2 = np.random.randint(5,20,(3,4))
arr2

array([[17,  8, 12,  5],
       [10, 11, 15, 17],
       [17,  9,  6, 12]])

In [20]:
arr1 &arr2

array([[0, 0, 0, 1],
       [0, 2, 4, 1],
       [1, 9, 6, 0]])

In [21]:
arr1 | arr2

array([[19, 12, 13,  5],
       [14, 15, 15, 21],
       [23,  9,  6, 13]])

In [22]:
~arr1

array([[ -3,  -5,  -2,  -2],
       [ -5,  -7,  -5,  -6],
       [ -8, -10,  -7,  -2]])

<font color="red" size=3><b>String operations</b></font>

In [23]:
arr = np.array(['paul','maitra'])
arr

array(['paul', 'maitra'], dtype='<U6')

In [24]:
np.char.upper(arr)

array(['PAUL', 'MAITRA'], dtype='<U6')

In [25]:
np.char.capitalize(arr)

array(['Paul', 'Maitra'], dtype='<U6')

In [26]:
np.char.title(arr)

array(['Paul', 'Maitra'], dtype='<U6')

<font color="red" size=3><b>Aggregate functions</b></font>

In [28]:
np.mean(arr1)

4.166666666666667

In [61]:
np.median(arr1)

4.0

In [31]:
np.std(arr1)

2.4776781245530843

In [60]:
np.sum(arr1)

50

<font color="red" size=3><b>Mathematical functions</b></font>

In [33]:
np.cos(arr1)

array([[-0.41614684, -0.65364362,  0.54030231,  0.54030231],
       [-0.65364362,  0.96017029, -0.65364362,  0.28366219],
       [ 0.75390225, -0.91113026,  0.96017029,  0.54030231]])

In [34]:
np.sin(arr1)

array([[ 0.90929743, -0.7568025 ,  0.84147098,  0.84147098],
       [-0.7568025 , -0.2794155 , -0.7568025 , -0.95892427],
       [ 0.6569866 ,  0.41211849, -0.2794155 ,  0.84147098]])

In [62]:
np.tan(arr1)

array([[-2.18503986,  1.15782128,  1.55740772,  1.55740772],
       [ 1.15782128, -0.29100619,  1.15782128, -3.38051501],
       [ 0.87144798, -0.45231566, -0.29100619,  1.55740772]])

<font color="red" size=3><b>Searching and sorting</b></font>

In [35]:
aa = np.array([1,5,8,3,87,45,21,54])


In [36]:
np.sort(aa)

array([ 1,  3,  5,  8, 21, 45, 54, 87])

In [37]:
np.searchsorted(aa,2) # returns the index where the ele should be inserted

1

In [38]:
np.count_nonzero(aa)

8

<font color="red" size=3><b>Conditional Selection</b></font>

In [40]:
print(aa)
np.where(aa>20) # gives the indexes where the condition satisfies

[ 1  5  8  3 87 45 21 54]


(array([4, 5, 6, 7], dtype=int64),)

In [42]:
np.extract(aa>20,aa) #returns the elements which satisfies the condition

array([87, 45, 21, 54])

In [63]:
aa[aa>20]

array([87, 45, 21, 54])

In [64]:
aa[np.where(aa>20)]

array([87, 45, 21, 54])

<font color="red" size=3><b>Copy and view</b></font>

In [49]:
print('Before aa ',aa)
bb = np.copy(aa) # deep copy
print('Before bb ',bb)
bb[0] = 11
print('After aa ', aa)
print('After bb ',bb)

Before aa  [ 1  5  8  3 87 45 21 54]
Before bb  [ 1  5  8  3 87 45 21 54]
After aa  [ 1  5  8  3 87 45 21 54]
After bb  [11  5  8  3 87 45 21 54]


In [51]:
print('Before aa ',aa)
bb = aa.view() # shallow copy
print('Before bb ',bb)
bb[0] = 11
print('After aa ', aa)
print('After bb ',bb)

Before aa  [ 1  5  8  3 87 45 21 54]
Before bb  [ 1  5  8  3 87 45 21 54]
After aa  [11  5  8  3 87 45 21 54]
After bb  [11  5  8  3 87 45 21 54]


<font color="red" size=3><b>Matrix library in numPy</b></font>

In [52]:
import numpy.matlib as nm

In [53]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [54]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [56]:
nm.eye(2)

matrix([[1., 0.],
        [0., 1.]])

<font color="red" size=3><b>Fancy indexing</b></font>

In [57]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [59]:
ind = np.array([[3,4,1],[7,8,5]])
print(x[ind])

[[4 5 2]
 [8 9 6]]


<font color="red" size=3><b>Infinite values</b></font>

In [69]:
# an array with finite and infinite values
arr = np.array([1, 2, np.inf, -np.inf, np.nan, 3])
arr

array([  1.,   2.,  inf, -inf,  nan,   3.])

In [70]:
# gets a boolean array indicating which elements are finite
mask = np.isfinite(arr)
mask

array([ True,  True, False, False, False,  True])

In [71]:
# use the mask to filter the finite values
arr[mask]

array([1., 2., 3.])

<font color="red" size=3><b>Difference between infinite and nan values</b></font>

In [72]:
log_zero = np.log(0)
print("Logarithm of 0:", log_zero)  

nan_example = np.sqrt(-1)
print("Square root of -1:", nan_example) 

# Check if they are NaN
print("Is -inf NaN?", np.isnan(log_zero))  
print("Is NaN NaN?", np.isnan(nan_example))  

# Check if they are infinite
print("Is -inf infinite?", np.isinf(log_zero))  
print("Is NaN infinite?", np.isinf(nan_example))  

Logarithm of 0: -inf
Square root of -1: nan
Is -inf NaN? False
Is NaN NaN? True
Is -inf infinite? True
Is NaN infinite? False


C:\Users\Paulami Maitra\AppData\Local\Temp\ipykernel_7676\632881166.py:1: RuntimeWarning: divide by zero encountered in log
  log_zero = np.log(0)
C:\Users\Paulami Maitra\AppData\Local\Temp\ipykernel_7676\632881166.py:4: RuntimeWarning: invalid value encountered in sqrt
  nan_example = np.sqrt(-1)


<font color="red" size=3><b>Split in NumPy </b></font>

In [74]:
a = np.array([1,2,3,45,6,7,8,99]).reshape(2,4)
print(a)

[[ 1  2  3 45]
 [ 6  7  8 99]]


In [76]:
# horizontal split
np.hsplit(a,2) #splits column wise

[array([[1, 2],
        [6, 7]]),
 array([[ 3, 45],
        [ 8, 99]])]

In [77]:
# vertical split
np.vsplit(a,2) #splits row wise

[array([[ 1,  2,  3, 45]]), array([[ 6,  7,  8, 99]])]

<font color="red" size=3><b>Stack in NumPy </b></font>

In [78]:
b = np.array([[1,2,3,4],[15,16,17,18]])

In [79]:
print(a)
print(b)

[[ 1  2  3 45]
 [ 6  7  8 99]]
[[ 1  2  3  4]
 [15 16 17 18]]


In [83]:
# horizontal stack
print(np.hstack((a,b)))

[[ 1  2  3 45  1  2  3  4]
 [ 6  7  8 99 15 16 17 18]]


In [84]:
# vertical stack
print(np.vstack((a,b)))

[[ 1  2  3 45]
 [ 6  7  8 99]
 [ 1  2  3  4]
 [15 16 17 18]]
