<font color="blue" size=5><b>Logistic Regression</b></font>

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [8]:
df['target'] = dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
dataset.target # 3 categories present

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# For binary classification we'll remove the third category
df = df[df['target']!=2]
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
58                6.6               2.9                4.6               1.3   
7                 5.0               3.4                1.5               0.2   
40                5.0               3.5                1.3               0.3   
53                5.5               2.3                4.0               1.3   
69                5.6               2.5                3.9               1.1   

    target  
58       1  
7        0  
40       0  
53       1  
69       1

In [12]:
# independent and dependent features
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)


In [15]:
classifier = LogisticRegression()

In [16]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = classifier.predict(X_test)

In [18]:
classifier.predict_proba(X_test) # gives probabilities

array([[0.00131815, 0.99868185],
       [0.95948581, 0.04051419],
       [0.00475717, 0.99524283],
       [0.94064719, 0.05935281],
       [0.98381903, 0.01618097],
       [0.93873175, 0.06126825],
       [0.98111483, 0.01888517],
       [0.97286844, 0.02713156],
       [0.97618748, 0.02381252],
       [0.98858271, 0.01141729],
       [0.01885926, 0.98114074],
       [0.02082109, 0.97917891],
       [0.00246582, 0.99753418],
       [0.98840877, 0.01159123],
       [0.97891406, 0.02108594],
       [0.9735968 , 0.0264032 ],
       [0.96955533, 0.03044467],
       [0.96405434, 0.03594566],
       [0.0139555 , 0.9860445 ],
       [0.07392082, 0.92607918]])

In [19]:
y_pred

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [20]:
y_test

83    1
30    0
56    1
24    0
16    0
23    0
2     0
27    0
28    0
13    0
99    1
92    1
76    1
14    0
0     0
21    0
3     0
29    0
61    1
79    1
Name: target, dtype: int64

<font color="red" size=3><b>Classification Metrics</b></font>

In [22]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score
accuracy_score(y_pred, y_test)

1.0

In [23]:
confusion_matrix(y_pred, y_test)

array([[13,  0],
       [ 0,  7]])

In [26]:
precision_score(y_pred, y_test, average='weighted')

1.0

In [27]:
recall_score(y_pred, y_test, average='weighted')

1.0

In [25]:
f1_score(y_pred, y_test, average='weighted')

1.0

In [24]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00         7

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

