<font color="orange" size=5><b>Handling Missing Values-2</b></font>

<font color="green" size=4><b>Handling Numerical Missing Data</b></font>

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [31]:
df = pd.read_csv('/content/titanic_toy.csv')

In [32]:
df.head()

Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64  
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(2)
memory usage: 28.0 KB


In [34]:
df.isnull().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

**Only age and fare columns have missing values**

In [35]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [36]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [37]:
X_train.shape, X_test.shape

((712, 3), (179, 3))

In [38]:
X_train.isnull().mean()

Age       0.207865
Fare      0.050562
Family    0.000000
dtype: float64

<font color="green" size=4><b>Mean-Median Imputation</b></font>

In [39]:
imputer1 = SimpleImputer(strategy='median')
imputer2 = SimpleImputer(strategy='mean')

In [40]:
trf = ColumnTransformer([
    ('imputer1',imputer1,['Age']),
    ('imputer2',imputer2,['Fare'])
],remainder='passthrough')

In [41]:
trf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer1', SimpleImputer(strategy='median'),
                                 ['Age']),
                                ('imputer2', SimpleImputer(), ['Fare'])])

In [42]:
trf.named_transformers_['imputer1'].statistics_

array([28.75])

In [43]:
trf.named_transformers_['imputer2'].statistics_

array([32.61759689])

In [44]:
X_train = trf.transform(X_train)
X_test = trf.transform(X_test)

In [45]:
X_train

array([[ 40.    ,  27.7208,   0.    ],
       [  4.    ,  16.7   ,   2.    ],
       [ 47.    ,   9.    ,   0.    ],
       ...,
       [ 71.    ,  49.5042,   0.    ],
       [ 28.75  , 221.7792,   0.    ],
       [ 28.75  ,  25.925 ,   0.    ]])

<font color="green" size=4><b>Arbitrary Value Imputation</b></font>

In [46]:
X1_train,X1_test,y1_train,y1_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [47]:
imputer3 = SimpleImputer(strategy='constant',fill_value=99)
imputer4 = SimpleImputer(strategy='constant',fill_value=999)

In [48]:
trf1 = ColumnTransformer([
    ('imputer3',imputer3,['Age']),
    ('imputer4',imputer4,['Fare'])
],remainder='passthrough')

In [49]:
trf1.fit(X1_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('imputer3',
                                 SimpleImputer(fill_value=99,
                                               strategy='constant'),
                                 ['Age']),
                                ('imputer4',
                                 SimpleImputer(fill_value=999,
                                               strategy='constant'),
                                 ['Fare'])])

In [50]:
trf1.named_transformers_['imputer3'].statistics_

array([99.])

In [51]:
trf1.named_transformers_['imputer4'].statistics_

array([999.])

In [53]:
X1_train = trf1.transform(X1_train)
X1_test = trf1.transform(X1_test)

In [54]:
X_train

array([[ 40.    ,  27.7208,   0.    ],
       [  4.    ,  16.7   ,   2.    ],
       [ 47.    ,   9.    ,   0.    ],
       ...,
       [ 71.    ,  49.5042,   0.    ],
       [ 28.75  , 221.7792,   0.    ],
       [ 28.75  ,  25.925 ,   0.    ]])