<font color="blue" size=5><b>Numpy-1</b></font>

In [1]:
import numpy as np

<font color="red" size=3><b>Creation of n dimentional array</b></font>

In [4]:
# using already existing values
l = [1,2,4,5]
ar = np.array(l)
print(type(ar))
print(ar)

<class 'numpy.ndarray'>
[1 2 4 5]


**creating array of particular dimention**

In [56]:
ar = np.array([1,2,5,4], ndmin=3) # ndmin creates array of a particular dimention
ar

array([[[1, 2, 5, 4]]])

In [7]:
ar1 = np.asarray([3,4,55,6])
ar1

array([ 3,  4, 55,  6])

In [8]:
ar2 = np.asanyarray([2,3,76,45])
ar2

array([ 2,  3, 76, 45])

In [39]:
# using zeros function
ar3 = np.zeros((2,3,2)) # takes input for each dimention
ar3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [34]:
# using ones function
ar3 = np.ones((2,3))
ar3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# using arange (can take floating point values for start and end and fractional step )
ar4 = np.arange(1,10,2) # start stop step
print (ar4) 

[1 3 5 7 9]


In [37]:
ar4 = np.arange(1.2,10.2,0.2) # start stop step
print (ar4) 

[ 1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6  3.8
  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4  6.6
  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2  9.4
  9.6  9.8 10. ]


In [38]:
# using linspace (produces n numbers between a given interval)
ar5 = np.linspace(1,5,10)
ar5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
# using empty (creates empty array)
ar6 = np.empty((3,5)) # values are negligible
ar6

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.81019663e-310]])

In [43]:
# using eye(cretates identity matrix)
ar7 = np.eye(3)
ar7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# using random
ar8 = np.random.randn(3,4) # generates data whose mean is 0  and standard deviation is 1
print(ar8)

array([[-0.20252981,  0.60262028,  0.13593732,  0.13592748],
       [-0.8735314 ,  1.11910748, -1.37650776, -0.68069607],
       [-1.0635352 , -0.82631843, -0.39116039, -1.0660551 ]])

**coverting array to a dataframe**

In [45]:
import pandas as pd
pd.DataFrame(ar8) # we can convert it to a data frame

0         1         2         3
0 -0.202530  0.602620  0.135937  0.135927
1 -0.873531  1.119107 -1.376508 -0.680696
2 -1.063535 -0.826318 -0.391160 -1.066055

In [46]:
# using random
ar8 = np.random.rand(3,4)
print(ar8)

[[0.91345754 0.72215892 0.89802299 0.91167355]
 [0.19406823 0.58522217 0.59216447 0.30768816]
 [0.94136767 0.68786852 0.60465203 0.73314509]]


**reshaping an array**

In [57]:
ar = ar8.reshape(2,6)
ar

array([[91, 44,  7, 22,  7, 87],
       [56, 37, 12, 74, 78, 51]])

In [47]:
# using random
ar8 = np.random.randint(1,100, (3,4)) # generates integers only
print(ar8)

[[91 44  7 22]
 [ 7 87 56 37]
 [12 74 78 51]]


**flattening of an array**

In [59]:
ar8.reshape(-1)

array([91, 44,  7, 22,  7, 87, 56, 37, 12, 74, 78, 51])

In [9]:
# usimg matrix (by default creates 2D array)
b = np.matrix(1)
b

matrix([[1]])

<font color="red" size=3><b>Indexing and slicing </b></font>

In [49]:
a1 = np.random.randint(5,60,(3,4))
a1

array([[21,  5, 58, 16],
       [11, 21, 23, 28],
       [55, 26, 19, 27]])

In [50]:
a1[1][3]

28

In [51]:
a1[1,3]

28

In [52]:
a1[0:2,1:3]

array([[ 5, 58],
       [21, 23]])

In [54]:
a1[a1>50]

array([58, 55])

<font color="red" size=3><b>Copy (Deep copy)</b></font>

In [10]:
a1 = np.array([9,8,7,6])
a2 = a1 # shallow copy
print(a1)
print(a2)

[9 8 7 6]
[9 8 7 6]


In [11]:
a1[2] = 0
a1

array([9, 8, 0, 6])

In [12]:
a2 # any changes in a will be reflected 

array([9, 8, 0, 6])

In [13]:
c1 = np.array([9,8,7,6])
c2 = np.copy(c1)
print(c1)
print(c2)

[9 8 7 6]
[9 8 7 6]


In [14]:
c1[0] = 0
print(c1)
print(c2)

[0 8 7 6]
[9 8 7 6]


<font color="red" size=3><b>Other Functions </b></font>

In [15]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [19]:
iterable = (i*i for i in range(5))

In [21]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [25]:
np.fromstring('123 234', sep=' ')

array([123., 234.])

<font color="red" size=3><b>Attributes of ndarray</b></font>

In [26]:
x = np.array([2,3,4,57,8])
x.shape # size of array in each dimension

(5,)

In [27]:
x.size # total number of elements

5

In [28]:
x.ndim # the no of axes of array

1

In [29]:
x.dtype

dtype('int32')

<font color="red" size=3><b>Operations on ndarray</b></font>

In [60]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
a1 = a1.reshape((3,3))
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a2 = np.array([2,4,1,6,8,7,9,5,4])
a2 = a2.reshape((3,3))
a2

array([[2, 4, 1],
       [6, 8, 7],
       [9, 5, 4]])

In [62]:
# matrix multiplication
a1@a2

array([[ 41,  35,  27],
       [ 92,  86,  63],
       [143, 137,  99]])

In [63]:
# multiplication 
a1*a2

array([[ 2,  8,  3],
       [24, 40, 42],
       [63, 40, 36]])

In [64]:
# addition
a1+a2

array([[ 3,  6,  4],
       [10, 13, 13],
       [16, 13, 13]])

In [65]:
# subtraction
a1-a2

array([[-1, -2,  2],
       [-2, -3, -1],
       [-2,  3,  5]])

In [66]:
# division
a1/a2

array([[0.5       , 0.5       , 3.        ],
       [0.66666667, 0.625     , 0.85714286],
       [0.77777778, 1.6       , 2.25      ]])

In [87]:
# square root
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

<font color="red" size=3><b>Broadcasting in numpy</b></font>

In [67]:
b = np.array([2,3,4,5])
b

array([2, 3, 4, 5])

In [68]:
b*2 # all elements of b gets multiplied by 2

array([ 4,  6,  8, 10])

In [69]:
b+3

array([5, 6, 7, 8])

In [70]:
b-4

array([-2, -1,  0,  1])

In [71]:
b/0

C:\Users\Paulami Maitra\AppData\Local\Temp\ipykernel_4016\2933543726.py:1: RuntimeWarning: divide by zero encountered in divide
  b/0


array([inf, inf, inf, inf])

In [72]:
b**2

array([ 4,  9, 16, 25])

In [78]:
b1 = np.arange(1,13)
b1 = b1.reshape((3,4))
print(b1)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 3 4 5]


In [79]:
b1+b

array([[ 3,  5,  7,  9],
       [ 7,  9, 11, 13],
       [11, 13, 15, 17]])